[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lectorcito-pro"
dynamic = ["version"]
requires-python = ">=3.11,<3.14"
dependencies = [
  "appdirs==1.4.4",
  "customtkinter==5.2.2",
  "pillow==12.1.0",
]

[project.optional-dependencies]
windows = [
  "pywin32==311",
]
build = [
  "Nuitka==2.8.10",
]
dev = [
  "debugpy==1.8.20",
  "ipython==9.10.0",
  "ipykernel==7.2.0",
]

[tool.setuptools.dynamic]
version = {attr = "app_meta.APP_VERSION"}

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
