[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lectorcito-pro"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
  "appdirs",
  "babel",
  "customtkinter",
  "darkdetect",
  "packaging",
  "pillow",
  "psutil",
  "tkfilebrowser",
]

[tool.setuptools.dynamic]
version = {attr = "app_meta.APP_VERSION"}

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]