window.APP_META = {
    "nameInternal": "LectorcitoPro",
    "displayName": "Lectorcito Pro",
    "productName": "Lectorcito Pro",
    "version": "10.7.5",
    "fileVersion": "10.7.5.0",
    "productVersion": "10.7.5.0",
    "author": "Renzo Fernando Mosquera Daza",
    "companyName": "Renzo Fernando Mosquera Daza",
    "publisherName": "Renzo Fernando Mosquera Daza",
    "fileDescription": "Herramienta de escritorio profesional para auditoría de código, documentación técnica y consolidación de contextos para Inteligencia Artificial.",
    "repositoryUrl": "https://github.com/RenzoFernando/LectorcitoPro",
    "websiteUrl": "https://renzofernando.github.io/LectorcitoPro/",
    "manualTitle": "Lectorcito Pro",
    "documentTitle": "Lectorcito Pro | Auditoría de código y contexto para IA",
    "releaseUrl": "https://github.com/RenzoFernando/LectorcitoPro/releases/latest",
    "downloadUrl": "https://github.com/RenzoFernando/LectorcitoPro/releases/latest/download/LectorcitoPro-Setup.exe",
    "installerDownloadUrl": "https://github.com/RenzoFernando/LectorcitoPro/releases/latest/download/LectorcitoPro-Setup.exe",
    "portableDownloadUrl": "https://github.com/RenzoFernando/LectorcitoPro/releases/latest/download/LectorcitoPro-Portable.exe",
    "linuxDownloadUrl": "https://github.com/RenzoFernando/LectorcitoPro/releases/latest/download/LectorcitoPro-Linux-x86_64",
    "executableName": "LectorcitoPro.exe",
    "installerName": "LectorcitoPro-Setup.exe",
    "portableArtifactName": "LectorcitoPro-Portable.exe",
    "linuxArtifactName": "LectorcitoPro-Linux-x86_64",
    "releaseBasename": "LectorcitoPro-10.7.5",
    "trademark": "Lectorcito Pro"
};
